version: "3.9"
services:

  service: 
    build: .
    ports: 
      - "8000:8000"
    environment:
      - OTEL_COLLECTOR=otel-collector
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector
    command: ["--config=/conf/otel-collector-config.yml"]
    volumes:
        - ./otel-collector-config.yml:/conf/otel-collector-config.yml
    ports: 
        - "9464:9464"
        - "55680:55680"
        - "55681:55681"
    depends_on:
        - zipkin
        - jaeger-all-in-one
  zipkin:
    image: openzipkin/zipkin
    ports:
        - "9411:9411"

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"